services:
 postgres:
  image: bitnami/postgresql:latest
  ports:
   - '5432:5432'
  env_file:
   - .env.postgres
  volumes:
   - polls_pg_data:/bitnami/postgresql


 api:
  image: juanfoltran/your-notes
  ports:
    - '3333:3333'
  env_file:
   - .env.api
  depends_on:
    - postgres
  
volumes:
   polls_pg_data:
